export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST";
export const SET_PRODUCTS_LIST = "SET_PRODUCTS_LIST";

export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
